services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app # Mount kode aplikasi untuk hot-reloading (opsional, untuk dev)
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432" # Map port 5432 di container ke port 5433 di mesin Anda
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
